/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as CollateralRouteImport } from './routes/collateral'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LogActivityRouteImport } from './routes/log-activity'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsCompanyIdRouteImport } from './routes/leads.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const CollateralRoute = CollateralRouteImport.update({
  id: '/collateral',
  path: '/collateral',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LogActivityRoute = LogActivityRouteImport.update({
  id: '/log-activity',
  path: '/log-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsCompanyIdRoute = LeadsCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/collateral': typeof CollateralRoute
  '/leads': typeof LeadsRouteWithChildren
  '/log-activity': typeof LogActivityRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/leads/$companyId': typeof LeadsCompanyIdRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/collateral': typeof CollateralRoute
  '/log-activity': typeof LogActivityRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/leads/$companyId': typeof LeadsCompanyIdRoute
  '/leads': typeof LeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/collateral': typeof CollateralRoute
  '/leads': typeof LeadsRouteWithChildren
  '/log-activity': typeof LogActivityRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/leads/$companyId': typeof LeadsCompanyIdRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/collateral'
    | '/leads'
    | '/log-activity'
    | '/messages'
    | '/news'
    | '/people'
    | '/settings'
    | '/leads/$companyId'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/collateral'
    | '/log-activity'
    | '/messages'
    | '/news'
    | '/people'
    | '/settings'
    | '/leads/$companyId'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/collateral'
    | '/leads'
    | '/log-activity'
    | '/messages'
    | '/news'
    | '/people'
    | '/settings'
    | '/leads/$companyId'
    | '/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  CollateralRoute: typeof CollateralRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LogActivityRoute: typeof LogActivityRoute
  MessagesRoute: typeof MessagesRoute
  NewsRoute: typeof NewsRoute
  PeopleRoute: typeof PeopleRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collateral': {
      id: '/collateral'
      path: '/collateral'
      fullPath: '/collateral'
      preLoaderRoute: typeof CollateralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-activity': {
      id: '/log-activity'
      path: '/log-activity'
      fullPath: '/log-activity'
      preLoaderRoute: typeof LogActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$companyId': {
      id: '/leads/$companyId'
      path: '/$companyId'
      fullPath: '/leads/$companyId'
      preLoaderRoute: typeof LeadsCompanyIdRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsCompanyIdRoute: typeof LeadsCompanyIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsCompanyIdRoute: LeadsCompanyIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  CollateralRoute: CollateralRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LogActivityRoute: LogActivityRoute,
  MessagesRoute: MessagesRoute,
  NewsRoute: NewsRoute,
  PeopleRoute: PeopleRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
